import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'package:inventory_lite/data/models/product.dart';
import 'package:inventory_lite/data/models/stock_movement.dart';
import 'package:inventory_lite/providers/catalog_providers.dart';
import './barcode_scanner_screen.dart';

/// Screen for registering stock entries (in) and exits (out).
///
/// Uses the [stockMovementRepositoryProvider] to execute atomic Firestore
/// transactions that update product stock and create movement records.
class AddMovementScreen extends ConsumerStatefulWidget {
  const AddMovementScreen({super.key});

  @override
  ConsumerState<AddMovementScreen> createState() => _AddMovementScreenState();
}

class _AddMovementScreenState extends ConsumerState<AddMovementScreen> {
  final _formKey = GlobalKey<FormState>();

  // --- Controllers ---
  final _quantityController = TextEditingController();
  final _noteController = TextEditingController();

  // --- State ---
  Product? _selectedProduct;
  MovementType _movementType = MovementType.inStock;
  bool _isSubmitting = false;

  // --- Design Tokens ---
  static const Color _primaryBlue = Color(0xFF1E40AF);
  static const Color _successGreen = Color(0xFF16A34A);
  static const Color _dangerRed = Color(0xFFDC2626);
  static const Color _warningAmber = Color(0xFFD97706);

  @override
  void dispose() {
    _quantityController.dispose();
    _noteController.dispose();
    super.dispose();
  }

  // ---------------------------------------------------------------------------
  // BARCODE SCANNER INTEGRATION
  // ---------------------------------------------------------------------------

  /// Opens the barcode scanner and searches for a matching product.
  Future<void> _scanBarcode() async {
    final scannedCode = await openBarcodeScanner(context);

    if (scannedCode == null || !mounted) return;

    // Search for a product with this barcode in the cached list
    final productsAsync = ref.read(productsProvider);

    productsAsync.whenData((products) {
      final matchingProduct = products
          .where((p) => p.barcode == scannedCode)
          .toList();

      if (matchingProduct.isNotEmpty) {
        setState(() => _selectedProduct = matchingProduct.first);
      } else {
        _showErrorSnackBar(
          'Aucun produit trouvé avec ce code-barres',
          detail: scannedCode,
        );
      }
    });
  }

  // ---------------------------------------------------------------------------
  // PRODUCT PICKER (Manual selection fallback)
  // ---------------------------------------------------------------------------

  /// Opens a dialog to manually select a product (for products without barcode).
  Future<void> _openProductPicker() async {
    final productsAsync = ref.read(productsProvider);

    productsAsync.whenData((products) {
      if (products.isEmpty) {
        _showErrorSnackBar('Aucun produit disponible dans le catalogue');
        return;
      }

      showModalBottomSheet(
        context: context,
        isScrollControlled: true,
        backgroundColor: Colors.white,
        shape: const RoundedRectangleBorder(
          borderRadius: BorderRadius.vertical(top: Radius.circular(20)),
        ),
        builder: (sheetContext) {
          return _ProductPickerSheet(
            products: products,
            onProductSelected: (product) {
              setState(() => _selectedProduct = product);
              Navigator.of(sheetContext).pop();
            },
          );
        },
      );
    });
  }

  // ---------------------------------------------------------------------------
  // FORM SUBMISSION
  // ---------------------------------------------------------------------------

  /// Validates the form and executes the stock movement transaction.
  Future<void> _submitMovement() async {
    // Step 1: Validate form fields
    if (!_formKey.currentState!.validate()) return;

    // Step 2: Ensure a product is selected
    if (_selectedProduct == null) {
      _showErrorSnackBar('Veuillez sélectionner un produit');
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      // Step 3: Build the StockMovement object
      final movement = StockMovement(
        id: '',
        // ID generated by Firestore in the repository
        productId: _selectedProduct!.id,
        type: _movementType,
        quantity: int.parse(_quantityController.text.trim()),
        date: DateTime.now(),
        note: _noteController.text.trim().isEmpty
            ? null
            : _noteController.text.trim(),
      );

      // Step 4: Execute atomic transaction via repository
      await ref.read(stockMovementRepositoryProvider).addMovement(movement);

      // Step 5: Success feedback
      if (!mounted) return;

      final actionLabel = _movementType == MovementType.inStock
          ? 'Entrée de stock enregistrée'
          : 'Sortie de stock enregistrée';

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Row(
            children: [
              const Icon(Icons.check_circle, color: Colors.white),
              const SizedBox(width: 12),
              Expanded(child: Text(actionLabel)),
            ],
          ),
          backgroundColor: _successGreen,
          behavior: SnackBarBehavior.floating,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
        ),
      );

      Navigator.of(context).pop();
    } catch (e) {
      if (!mounted) return;

      // Handle specific errors from the atomic transaction
      String errorMessage = 'Erreur lors de l\'enregistrement du mouvement';

      if (e.toString().contains('Stock insuffisant')) {
        errorMessage =
            'Stock insuffisant. Disponible : ${_selectedProduct!.currentStock}';
      } else if (e.toString().contains('Produit introuvable')) {
        errorMessage = 'Ce produit n\'existe plus dans le catalogue';
      }

      _showErrorSnackBar(errorMessage);
    } finally {
      if (mounted) {
        setState(() => _isSubmitting = false);
      }
    }
  }

  // ---------------------------------------------------------------------------
  // HELPERS
  // ---------------------------------------------------------------------------

  void _showErrorSnackBar(String message, {String? detail}) {
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Icon(Icons.error_outline, color: Colors.white),
                const SizedBox(width: 12),
                Expanded(child: Text(message)),
              ],
            ),
            if (detail != null) ...[
              const SizedBox(height: 4),
              Text(
                detail,
                style: TextStyle(
                  fontSize: 12,
                  color: Colors.white.withValues(alpha: 0.8),
                ),
              ),
            ],
          ],
        ),
        backgroundColor: _dangerRed,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // BUILD
  // ---------------------------------------------------------------------------

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Nouveau mouvement de stock'),
        centerTitle: false,
        elevation: 0,
      ),
      body: SafeArea(
        child: Column(
          children: [
            // --- Scrollable Form ---
            Expanded(
              child: SingleChildScrollView(
                padding: const EdgeInsets.all(20.0),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // --- Movement Type Selector ---
                      _buildSectionLabel('Type de mouvement', theme),
                      const SizedBox(height: 12),
                      _buildMovementTypeSelector(),
                      const SizedBox(height: 24),

                      // --- Product Selection ---
                      _buildSectionLabel('Produit concerné', theme),
                      const SizedBox(height: 12),
                      _buildProductField(),
                      if (_selectedProduct != null) ...[
                        const SizedBox(height: 8),
                        _buildStockInfoCard(),
                      ],
                      const SizedBox(height: 24),

                      // --- Quantity ---
                      _buildSectionLabel('Quantité', theme),
                      const SizedBox(height: 12),
                      _buildQuantityField(),
                      const SizedBox(height: 24),

                      // --- Note ---
                      _buildSectionLabel('Note (optionnel)', theme),
                      const SizedBox(height: 12),
                      _buildNoteField(),
                    ],
                  ),
                ),
              ),
            ),

            // --- Submit Button (Fixed at bottom) ---
            _buildSubmitButton(),
          ],
        ),
      ),
    );
  }

  // ---------------------------------------------------------------------------
  // WIDGET BUILDERS
  // ---------------------------------------------------------------------------

  Widget _buildSectionLabel(String text, ThemeData theme) {
    return Text(
      text,
      style: theme.textTheme.titleSmall?.copyWith(
        color: const Color(0xFF475569), // Slate Grey
        fontWeight: FontWeight.w600,
      ),
    );
  }

  Widget _buildMovementTypeSelector() {
    return SegmentedButton<MovementType>(
      segments: const [
        ButtonSegment(
          value: MovementType.inStock,
          label: Text('Entrée'),
          icon: Icon(Icons.arrow_downward),
        ),
        ButtonSegment(
          value: MovementType.outStock,
          label: Text('Sortie'),
          icon: Icon(Icons.arrow_upward),
        ),
      ],
      selected: {_movementType},
      onSelectionChanged: (selection) {
        setState(() => _movementType = selection.first);
      },
      style: SegmentedButton.styleFrom(
        backgroundColor: Colors.white,
        foregroundColor: _movementType == MovementType.inStock
            ? _successGreen
            : _dangerRed,
        selectedBackgroundColor: _movementType == MovementType.inStock
            ? const Color(0xFFDCFCE7) // Success Badge BG
            : const Color(0xFFFEE2E2),
        // Danger Badge BG
        selectedForegroundColor: _movementType == MovementType.inStock
            ? _successGreen
            : _dangerRed,
        side: BorderSide(color: Colors.grey.shade300),
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
      ),
    );
  }

  Widget _buildProductField() {
    return TextFormField(
      readOnly: true,
      controller: TextEditingController(text: _selectedProduct?.name ?? ''),
      decoration: InputDecoration(
        hintText: 'Scannez ou sélectionnez un produit',
        prefixIcon: const Icon(Icons.inventory_2_outlined),
        border: const OutlineInputBorder(),
        // --- SCANNER BUTTON ---
        suffixIcon: IconButton(
          icon: const Icon(Icons.qr_code_scanner),
          tooltip: 'Scanner un code-barres',
          onPressed: _scanBarcode,
          style: IconButton.styleFrom(foregroundColor: _primaryBlue),
        ),
      ),
      onTap: _openProductPicker,
      validator: (value) {
        if (_selectedProduct == null) {
          return 'Veuillez sélectionner un produit';
        }
        return null;
      },
    );
  }

  Widget _buildStockInfoCard() {
    final product = _selectedProduct!;
    final isEntry = _movementType == MovementType.inStock;

    return Container(
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: const Color(0xFFF8FAFC), // Background
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: const Color(0xFFE2E8F0)),
      ),
      child: Row(
        children: [
          Icon(
            isEntry ? Icons.trending_up : Icons.trending_down,
            color: isEntry ? _successGreen : _dangerRed,
            size: 20,
          ),
          const SizedBox(width: 8),
          Expanded(
            child: Text(
              'Stock actuel : ${product.currentStock} unités',
              style: const TextStyle(fontSize: 13, fontWeight: FontWeight.w500),
            ),
          ),
          if (product.currentStock <= 5)
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
              decoration: BoxDecoration(
                color: const Color(0xFFFEF3C7), // Warning BG
                borderRadius: BorderRadius.circular(4),
              ),
              child: const Text(
                'Stock faible',
                style: TextStyle(
                  fontSize: 11,
                  color: _warningAmber,
                  fontWeight: FontWeight.w600,
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildQuantityField() {
    return TextFormField(
      controller: _quantityController,
      decoration: const InputDecoration(
        labelText: 'Quantité *',
        hintText: 'Ex : 10',
        prefixIcon: Icon(Icons.numbers),
        border: OutlineInputBorder(),
      ),
      keyboardType: TextInputType.number,
      inputFormatters: [FilteringTextInputFormatter.digitsOnly],
      validator: (value) {
        if (value == null || value.trim().isEmpty) {
          return 'La quantité est obligatoire';
        }
        final quantity = int.tryParse(value.trim());
        if (quantity == null) {
          return 'Quantité invalide';
        }
        if (quantity <= 0) {
          return 'La quantité doit être supérieure à 0';
        }
        return null;
      },
    );
  }

  Widget _buildNoteField() {
    return TextFormField(
      controller: _noteController,
      decoration: const InputDecoration(
        labelText: 'Note',
        hintText: 'Ex : Réapprovisionnement, Produit endommagé...',
        prefixIcon: Icon(Icons.note_outlined),
        border: OutlineInputBorder(),
      ),
      maxLines: 2,
      textCapitalization: TextCapitalization.sentences,
    );
  }

  Widget _buildSubmitButton() {
    final isEntry = _movementType == MovementType.inStock;

    return Container(
      padding: const EdgeInsets.all(20.0),
      decoration: BoxDecoration(
        color: Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 10,
            offset: const Offset(0, -2),
          ),
        ],
      ),
      child: SafeArea(
        child: SizedBox(
          width: double.infinity,
          height: 52,
          child: ElevatedButton.icon(
            onPressed: _isSubmitting ? null : _submitMovement,
            icon: _isSubmitting
                ? const SizedBox(
                    width: 20,
                    height: 20,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                : Icon(
                    isEntry
                        ? Icons.add_circle_outline
                        : Icons.remove_circle_outline,
                  ),
            label: Text(
              _isSubmitting ? 'Enregistrement...' : 'Confirmer la transaction',
              style: const TextStyle(fontSize: 16, fontWeight: FontWeight.w600),
            ),
            style: ElevatedButton.styleFrom(
              backgroundColor: isEntry ? _successGreen : _dangerRed,
              foregroundColor: Colors.white,
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(12),
              ),
            ),
          ),
        ),
      ),
    );
  }
}

// ---------------------------------------------------------------------------
// SEARCHABLE PRODUCT PICKER BOTTOM SHEET
// ---------------------------------------------------------------------------

/// A draggable bottom sheet that lets the user search products by name
/// or barcode, then select one from the filtered list.
class _ProductPickerSheet extends StatefulWidget {
  final List<Product> products;
  final ValueChanged<Product> onProductSelected;

  const _ProductPickerSheet({
    required this.products,
    required this.onProductSelected,
  });

  @override
  State<_ProductPickerSheet> createState() => _ProductPickerSheetState();
}

class _ProductPickerSheetState extends State<_ProductPickerSheet> {
  final _searchController = TextEditingController();
  late List<Product> _filteredProducts;

  @override
  void initState() {
    super.initState();
    _filteredProducts = widget.products;
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  /// Filters the product list in real-time as the user types.
  void _filterProducts(String query) {
    setState(() {
      if (query.trim().isEmpty) {
        _filteredProducts = widget.products;
        return;
      }

      final lowerQuery = query.trim().toLowerCase();
      _filteredProducts = widget.products.where((product) {
        final matchesName = product.name.toLowerCase().contains(lowerQuery);
        final matchesBarcode = product.barcode?.contains(query.trim()) ?? false;
        return matchesName || matchesBarcode;
      }).toList();
    });
  }

  @override
  Widget build(BuildContext context) {
    return DraggableScrollableSheet(
      initialChildSize: 0.65,
      minChildSize: 0.4,
      maxChildSize: 0.9,
      expand: false,
      builder: (context, scrollController) {
        return Column(
          children: [
            // --- Drag handle ---
            Container(
              margin: const EdgeInsets.only(top: 12),
              width: 40,
              height: 4,
              decoration: BoxDecoration(
                color: Colors.grey.shade300,
                borderRadius: BorderRadius.circular(2),
              ),
            ),

            // --- Title ---
            Padding(
              padding: const EdgeInsets.fromLTRB(20, 16, 20, 8),
              child: Row(
                children: [
                  const Icon(
                    Icons.inventory_2_outlined,
                    color: Color(0xFF1E40AF),
                  ),
                  const SizedBox(width: 12),
                  Text(
                    'Sélectionner un produit',
                    style: Theme.of(context).textTheme.titleMedium?.copyWith(
                      fontWeight: FontWeight.w600,
                    ),
                  ),
                ],
              ),
            ),

            // --- Search field ---
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 8),
              child: TextField(
                controller: _searchController,
                onChanged: _filterProducts,
                autofocus: true,
                decoration: InputDecoration(
                  hintText: 'Rechercher par nom ou code-barres...',
                  prefixIcon: const Icon(Icons.search),
                  suffixIcon: _searchController.text.isNotEmpty
                      ? IconButton(
                          icon: const Icon(Icons.clear),
                          onPressed: () {
                            _searchController.clear();
                            _filterProducts('');
                          },
                        )
                      : null,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  filled: true,
                  fillColor: const Color(0xFFF8FAFC),
                  contentPadding: const EdgeInsets.symmetric(vertical: 0),
                ),
              ),
            ),

            const Divider(height: 1),

            // --- Product list ---
            Expanded(
              child: _filteredProducts.isEmpty
                  ? _buildEmptySearchState()
                  : ListView.builder(
                      controller: scrollController,
                      padding: const EdgeInsets.symmetric(vertical: 8),
                      itemCount: _filteredProducts.length,
                      itemBuilder: (context, index) {
                        final product = _filteredProducts[index];
                        return _buildProductTile(product);
                      },
                    ),
            ),
          ],
        );
      },
    );
  }

  Widget _buildProductTile(Product product) {
    final isLowStock = product.currentStock <= 5;

    return ListTile(
      leading: Container(
        padding: const EdgeInsets.all(8),
        decoration: BoxDecoration(
          color: const Color(0xFFEFF6FF),
          borderRadius: BorderRadius.circular(8),
        ),
        child: const Icon(
          Icons.inventory_2_outlined,
          color: Color(0xFF1E40AF),
          size: 20,
        ),
      ),
      title: Text(
        product.name,
        style: const TextStyle(fontWeight: FontWeight.w500),
      ),
      subtitle: Text('Stock actuel : ${product.currentStock}'),
      trailing: isLowStock
          ? Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
              decoration: BoxDecoration(
                color: const Color(0xFFFEF3C7),
                borderRadius: BorderRadius.circular(4),
              ),
              child: const Text(
                'Faible',
                style: TextStyle(
                  fontSize: 11,
                  color: Color(0xFFD97706),
                  fontWeight: FontWeight.w600,
                ),
              ),
            )
          : null,
      onTap: () => widget.onProductSelected(product),
    );
  }

  Widget _buildEmptySearchState() {
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(24),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Icon(Icons.search_off, size: 48, color: Colors.grey.shade400),
            const SizedBox(height: 12),
            const Text(
              'Aucun produit trouvé',
              style: TextStyle(fontWeight: FontWeight.w600),
            ),
            const SizedBox(height: 4),
            Text(
              'Essayez un autre nom ou code-barres',
              style: TextStyle(fontSize: 13, color: Colors.grey.shade600),
            ),
          ],
        ),
      ),
    );
  }
}
