// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBibEj5r1sw5Gn5HLT6wTKOcY8ntzqb1YM',
    appId: '1:899989683583:web:95ae55fbbce69e5ca92e4a',
    messagingSenderId: '899989683583',
    projectId: 'inventorylite-d1e72',
    authDomain: 'inventorylite-d1e72.firebaseapp.com',
    storageBucket: 'inventorylite-d1e72.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOMBb_anv79w-1nblxL6AzzKjLZqCf_dQ',
    appId: '1:899989683583:android:dd90a433d790737ca92e4a',
    messagingSenderId: '899989683583',
    projectId: 'inventorylite-d1e72',
    storageBucket: 'inventorylite-d1e72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4CfXuN3D5Uxrg9PMI5Q0n9Gf9Fk0Z_8k',
    appId: '1:899989683583:ios:742d5138ad14b432a92e4a',
    messagingSenderId: '899989683583',
    projectId: 'inventorylite-d1e72',
    storageBucket: 'inventorylite-d1e72.firebasestorage.app',
    iosBundleId: 'com.example.inventoryLite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4CfXuN3D5Uxrg9PMI5Q0n9Gf9Fk0Z_8k',
    appId: '1:899989683583:ios:742d5138ad14b432a92e4a',
    messagingSenderId: '899989683583',
    projectId: 'inventorylite-d1e72',
    storageBucket: 'inventorylite-d1e72.firebasestorage.app',
    iosBundleId: 'com.example.inventoryLite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBibEj5r1sw5Gn5HLT6wTKOcY8ntzqb1YM',
    appId: '1:899989683583:web:90bb1c0513dece07a92e4a',
    messagingSenderId: '899989683583',
    projectId: 'inventorylite-d1e72',
    authDomain: 'inventorylite-d1e72.firebaseapp.com',
    storageBucket: 'inventorylite-d1e72.firebasestorage.app',
  );
}
